packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 22.10.10
  eslint: 9.31.0
  lint-staged: 15.2.10
  prettier: 3.3.3
  typescript: 5.8.3
  zod: 3.23.8

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
