services:
  # API Service
  - type: web
    name: ship-nuxt-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: pnpm install && pnpm --filter api build
    startCommand: pnpm --filter api db:migrate && pnpm --filter api start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ship-nuxt-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: ship-nuxt-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false
      - key: WEB_URL
        value: https://ship-nuxt-web.onrender.com
    healthCheckPath: /health

  # Web service will be deployed on Vercel instead of Render

  # Redis/Key Value Service (Free Tier)
  - type: keyvalue
    name: ship-nuxt-redis
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: ship-nuxt-db
    databaseName: ship_nuxt
    user: ship_nuxt_user
    plan: free
    region: oregon