apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ${NAMESPACE:-production}
spec:
  replicas: ${WEB_REPLICAS:-1}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ${ECR_REGISTRY}/ship-nuxt-web:${IMAGE_TAG:-latest}
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_ENV
          value: "${APP_ENV:-production}"
        - name: VITE_API_URL
          value: "${API_URL:-https://api.ship-nuxt.dedyn.io}"
        - name: VITE_WS_URL
          value: "${WS_URL:-https://api.ship-nuxt.dedyn.io}"
        - name: VITE_WEB_URL
          value: "${WEB_URL:-https://ship-nuxt.dedyn.io}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: ${NAMESPACE:-production}
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP