apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: $NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: $ECR_REGISTRY/ship-nuxt-web:$IMAGE_TAG
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_ENV
          value: "$APP_ENV"
        - name: VITE_API_URL
          value: "$API_URL"
        - name: VITE_WS_URL
          value: "$WS_URL"
        - name: VITE_WEB_URL
          value: "$WEB_URL"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: $NAMESPACE
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP